language: node_js
node_js:
  - '6'
# Travis-CI Caching
cache:
  directories:
    - node_modules
# S: Build Lifecycle
install:
  - npm install
before_script:

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run dist:dev

#after_script:
#after_success:
#  - git config user.name "${U_NAME}"
#  - git config user.email "${U_EMAIL}"
#  - git add ./dist/*
#  - git commit -m "update dist `date +%s%N`"
#  - git log 2.0 ^origin/2.0
#  - git push --force "https://${GH_TOKEN}@${GH_REF}" 2.0:${PUB_BRANCH}
# E: Build LifeCycle

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file_glob: true
  file: dist/*
  skip_cleanup: true
  overwrite: true
  on:
    branch: 2.0
    tags: true

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - 2.0

env:
 global:
   # 我将其添加到了travis-ci的环境变量中
   #- GH_REF: github.com/HQIT/vue-strap.git
